### PR TITLE
Make stringlist provider control compatible

### PR DESCRIPTION
**Pull request by jfudickar**
- Changing the LogList property datatype back to TStrings to make it compatible with more VCL controls.
- Fixes handling of global CriticalSection. This prevents exceptions when the unit was deinitialized while the loghandler is still acitve

### CODE REVIEW

**Comment by jfudickar** [comment]
A demo application will follow with the next pull request

**Review by exilon — COMMENTED** [review]
I think this solves exception problem:

```
if Assigned(GlobalLogMemoryProvider) and (GlobalLogMemoryProvider.RefCount = 0) then
begin
  GlobalLogMemoryProvider.Free;
  {$IF Defined(MSWINDOWS) OR Defined(DELPHILINUX)}
  DeleteCriticalSection(CS);
  {$ELSE}
  DoneCriticalsection(CS);
end;
```

**Review by exilon — COMMENTED** [review]
I think this solves exception on close:
```
if Assigned(GlobalLogMemoryProvider) and (GlobalLogMemoryProvider.RefCount = 0) then
  begin
    GlobalLogStringListProvider.Free;
    {$IF Defined(MSWINDOWS) OR Defined(DELPHILINUX)}
    DeleteCriticalSection(CS);
    {$ELSE}
    DoneCriticalsection(CS);
```
    {$ENDIF}
  end;

**Comment by jfudickar** [comment]
But then you have the problem that the CriticalSection is not cleared when closing the program.

The problem happens when the ProviderUnit is finalized before the central loghandler unit.

**Comment by jfudickar** [comment]
What should we do now?
I think that you're solution will raise a memory leak, my solution is not so nice, but clean.

**Comment by jfudickar** [comment]
Any news?

**Comment by jfudickar** [comment]
Hellooo?

**Comment by jfudickar** [comment]
Any chance to get this handled?

**Comment by jfudickar** [comment]
One year later :-(

**Comment by exilon** [comment]
Stringlist provider and other providers have same code and don't raise exceptions on close. Can you provide a code sample with memory provider?

**Comment by jfudickar** [comment]
I can't in the moment.
I will integrate the other changes into your current master.
Then this change can be integrated.
And then I will try to reproduce it.

**Pull request closed without merging**
